# Generated by Django 3.0 on 2021-05-25 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.AddField(
            model_name='place',
            name='api',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('service_time', models.IntegerField()),
                ('queue_length', models.IntegerField()),
                ('current_queue_number', models.CharField(max_length=10)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air_app.Place')),
            ],
        ),
    ]
