# Generated by Django 3.0 on 2021-05-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_app', '0002_auto_20210525_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='LELELEL', max_length=100),
            preserve_default=False,
        ),
    ]
