# Generated by Django 3.0 on 2021-05-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_app', '0003_place_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='date',
        ),
        migrations.AlterField(
            model_name='queue',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
