# Generated by Django 3.0 on 2021-05-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_app', '0004_auto_20210526_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='num_of_week',
            field=models.IntegerField(default=1),
        ),
    ]
