# Generated by Django 3.0 on 2021-05-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_app', '0004_auto_20210526_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='date',
            new_name='num_of_week',
        ),
    ]
