# Generated by Django 3.0 on 2021-05-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_app', '0005_auto_20210526_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='num_of_week',
        ),
    ]
